/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import control.Control;
import javax.swing.JOptionPane;
import model.Produto;

/**
 *
 * @author ASUS
 */
public class TCombustivel extends javax.swing.JFrame {

    /**
     * Creates new form TCombustivel
     */
    public TCombustivel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtLitros = new javax.swing.JTextField();
        jtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        progressPanel = new view.CustomPanelGasolina();
        jLabel5 = new javax.swing.JLabel();
        customPanelAditivada1 = new view.CustomPanelAditivada();
        customPanelDiesel1 = new view.CustomPanelDiesel();
        customPanelEtanol1 = new view.CustomPanelEtanol();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tipoCombustivel = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        botaoCalcula = new javax.swing.JButton();
        botaoVenda = new javax.swing.JButton();
        jtValor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Total");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Combustível");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));
        jPanel1.add(jtLitros, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 70, 30));
        jPanel1.add(jtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 90, 40));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Etanol");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        javax.swing.GroupLayout progressPanelLayout = new javax.swing.GroupLayout(progressPanel);
        progressPanel.setLayout(progressPanelLayout);
        progressPanelLayout.setHorizontalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        progressPanelLayout.setVerticalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.add(progressPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 180, 150));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Gasolina Aditivada");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        javax.swing.GroupLayout customPanelAditivada1Layout = new javax.swing.GroupLayout(customPanelAditivada1);
        customPanelAditivada1.setLayout(customPanelAditivada1Layout);
        customPanelAditivada1Layout.setHorizontalGroup(
            customPanelAditivada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        customPanelAditivada1Layout.setVerticalGroup(
            customPanelAditivada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.add(customPanelAditivada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        javax.swing.GroupLayout customPanelDiesel1Layout = new javax.swing.GroupLayout(customPanelDiesel1);
        customPanelDiesel1.setLayout(customPanelDiesel1Layout);
        customPanelDiesel1Layout.setHorizontalGroup(
            customPanelDiesel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        customPanelDiesel1Layout.setVerticalGroup(
            customPanelDiesel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.add(customPanelDiesel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        javax.swing.GroupLayout customPanelEtanol1Layout = new javax.swing.GroupLayout(customPanelEtanol1);
        customPanelEtanol1.setLayout(customPanelEtanol1Layout);
        customPanelEtanol1Layout.setHorizontalGroup(
            customPanelEtanol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        customPanelEtanol1Layout.setVerticalGroup(
            customPanelEtanol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.add(customPanelEtanol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Gasolina");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Diesel");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        tipoCombustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione o Item>", "Gasolina Comum", "Gasolina Aditivada", "Etanol", "Diesel" }));
        tipoCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCombustivelActionPerformed(evt);
            }
        });
        jPanel1.add(tipoCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 140, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Valor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        botaoCalcula.setText("Calcular");
        botaoCalcula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCalculaMouseClicked(evt);
            }
        });
        jPanel1.add(botaoCalcula, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        botaoVenda.setText("Finalizar");
        botaoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));
        jPanel1.add(jtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 80, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Litros");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        encherProgressoGasolina();
        encherProgressoDiesel();
        encherProgressoGasolinaAditivada();
        encherProgressoEtanol();
    }//GEN-LAST:event_formWindowOpened

    private void tipoCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCombustivelActionPerformed
        // TODO add your handling code here:
        mostrarPreço();
    }//GEN-LAST:event_tipoCombustivelActionPerformed

    private void botaoCalculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCalculaMouseClicked
        // TODO add your handling code here:
        float valor = Float.parseFloat(jtValor.getText());
        float litros = Float.parseFloat(jtLitros.getText());
        float total = valor *litros;
        
        jtTotal.setText(Float.toString(total));
    }//GEN-LAST:event_botaoCalculaMouseClicked

    private void botaoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVendaActionPerformed
        // TODO add your handling code here:
        evt.getClass();
        
        String nomeCombustivel = (String)tipoCombustivel.getSelectedItem();        
        float litros = Float.parseFloat(jtLitros.getText());
        float total = Float.parseFloat(jtTotal.getText());
        float  qtd_vendida = Float.parseFloat(jtLitros.getText());
        control.Control.updateEstoque( litros, (String)tipoCombustivel.getSelectedItem());
        Control.addVendaCombustivel(nomeCombustivel,litros, total);
        
        encherProgressoGasolina();
        encherProgressoDiesel();
        encherProgressoGasolinaAditivada();
        encherProgressoEtanol();   
        
        JOptionPane.showMessageDialog(null,"Venda realizada com sucesso");
    }//GEN-LAST:event_botaoVendaActionPerformed
    
    private void mostrarPreço(){
      if(tipoCombustivel.getSelectedItem().equals("Etanol")){
          Produto combustivel=Control.buscaProduto("Etanol");
          float valor = combustivel.getValor();
          jtValor.setText(Float.toString(valor));
      }else if(tipoCombustivel.getSelectedItem().equals("Diesel")){
          Produto combustivel=Control.buscaProduto("Diesel");
          float valor = combustivel.getValor();
          jtValor.setText(Float.toString(valor));
     }else if (tipoCombustivel.getSelectedItem().equals("Gasolina Comum")){
          Produto combustivel=Control.buscaProduto("Gasolina Comum");
          float valor = combustivel.getValor();
          jtValor.setText(Float.toString(valor));
     }else if(tipoCombustivel.getSelectedItem().equals("Gasolina Aditivada")){
          Produto combustivel=Control.buscaProduto("Gasolina Aditivada");
          float valor = combustivel.getValor();
          jtValor.setText(Float.toString(valor));
    }else if (tipoCombustivel.getSelectedItem().equals("<Selecione o Item>")){
       
          jtValor.setText("");
    }
    }
    
    //Verificar método
    private void encherProgressoGasolina(){
        Produto gasolina;
        gasolina = Control.buscaProduto("Gasolina Comum");
        float maximo = gasolina.getMaximo();
        float armazenado = gasolina.getQntArmazenada();
        float totalTanque= (armazenado/maximo)*100;
        new Thread(new Runnable() {
            @Override
            public void run() {
for (int num = 1; num <= totalTanque; num++) {
            
               try {
                   progressPanel.UpdateProgress(num);
                   progressPanel.repaint();
                   Thread.sleep(5);
               } catch (InterruptedException ex) {
                   Logger.getLogger(TCombustivel.class.getName()).log(Level.SEVERE, null, ex);
               }
        }            }
        }) .start();
        
    }
    
    private void encherProgressoGasolinaAditivada(){
        Produto gasolinaAditivada;
        gasolinaAditivada = Control.buscaProduto("Gasolina Aditivada");
        float maximo = gasolinaAditivada.getMaximo();
        float armazenado = gasolinaAditivada.getQntArmazenada();
        float totalTanque= (armazenado/maximo)*100;
        new Thread(new Runnable() {
            @Override
            public void run() {
for (int num = 1; num <= totalTanque; num++) {
            
               try {
                   customPanelAditivada1.UpdateProgress(num);
                   customPanelAditivada1.repaint();
                   Thread.sleep(5);
               } catch (InterruptedException ex) {
                   Logger.getLogger(TCombustivel.class.getName()).log(Level.SEVERE, null, ex);
               }
        }            }
        }) .start();
        
    }
    
    private void encherProgressoEtanol(){
        Produto etanol;
        etanol = Control.buscaProduto("Etanol");
        float maximo = etanol.getMaximo();
        float armazenado = etanol.getQntArmazenada();
        float totalTanque= (armazenado/maximo)*100;
        new Thread(new Runnable() {
            @Override
            public void run() {
for (int num = 1; num <= totalTanque; num++) {
            
               try {
                   customPanelEtanol1.UpdateProgress(num);
                   customPanelEtanol1.repaint();
                   Thread.sleep(5);
               } catch (InterruptedException ex) {
                   Logger.getLogger(TCombustivel.class.getName()).log(Level.SEVERE, null, ex);
               }
        }            }
        }) .start();
        
    }
    
    private void encherProgressoDiesel(){
        Produto diesel;
        diesel = Control.buscaProduto("Diesel");
        float maximo = diesel.getMaximo();
        float armazenado = diesel.getQntArmazenada();
        float totalTanque= (armazenado/maximo)*100;
        new Thread(new Runnable() {
            @Override
            public void run() {
for (int num = 1; num <= totalTanque; num++) {
            
               try {
                   customPanelDiesel1.UpdateProgress(num);
                   customPanelDiesel1.repaint();
                   Thread.sleep(5);
               } catch (InterruptedException ex) {
                   Logger.getLogger(TCombustivel.class.getName()).log(Level.SEVERE, null, ex);
               }
        }            }
        }) .start();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCombustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCombustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCombustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCombustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               TCombustivel tc = new TCombustivel();
               tc.setVisible(true);
            }
        });
        
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalcula;
    private javax.swing.JButton botaoVenda;
    private view.CustomPanelAditivada customPanelAditivada1;
    private view.CustomPanelDiesel customPanelDiesel1;
    private view.CustomPanelEtanol customPanelEtanol1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtLitros;
    private javax.swing.JTextField jtTotal;
    private javax.swing.JTextField jtValor;
    private view.CustomPanelGasolina progressPanel;
    private javax.swing.JComboBox<String> tipoCombustivel;
    // End of variables declaration//GEN-END:variables
}
