/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import javax.swing.JPanel;
import modelDAO.Conexao;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dell
 */
public class TRelatorioF extends javax.swing.JFrame {


// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelRelatComb;
    private javax.swing.JPanel jPanelRelatVend;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form TFolhadePagamento
     */
    public TRelatorioF() {
        initComponents();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelRelatComb = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelRelatVend = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRelatComb.setBackground(new java.awt.Color(232, 81, 74));
        jPanelRelatComb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRelatCombMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRelatCombMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRelatCombMouseExited(evt);
            }
        });
        jPanelRelatComb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Relatorio de combustivel");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanelRelatComb.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel3.setBackground(new java.awt.Color(232, 81, 74));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Entrar");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanelRelatComb.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 120, 40));

        jPanel1.add(jPanelRelatComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 213, 145));

        jPanelRelatVend.setBackground(new java.awt.Color(232, 81, 74));
        jPanelRelatVend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRelatVendMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRelatVendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRelatVendMouseExited(evt);
            }
        });
        jPanelRelatVend.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Relatorio de Vendas");
        jPanelRelatVend.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jPanel1.add(jPanelRelatVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 210, 145));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 580, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelRelatCombMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatCombMouseClicked
        // TODO add your handling code here:
        evt.getClass();
        
        Connection con = Conexao.getConnection();

            String src = "RelatorioCombustivel.jasper";

            JasperPrint jasperPrint = null;
            try {

                
                jasperPrint = JasperFillManager.fillReport(src, null, con);
            } catch (JRException ex) {
                System.out.println("Error: " + ex);
            }

            JasperViewer view = new JasperViewer(jasperPrint, false);
            view.setVisible(true);

       
        

       
    }//GEN-LAST:event_jPanelRelatCombMouseClicked

    private void jPanelRelatCombMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatCombMouseEntered
        // TODO add your handling code here:
        evt.getLocationOnScreen();
        setColor(jPanelRelatComb);
    }//GEN-LAST:event_jPanelRelatCombMouseEntered

    private void jPanelRelatCombMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatCombMouseExited
        // TODO add your handling code here:
        evt.getLocationOnScreen();
        resetColor(jPanelRelatComb);
    }//GEN-LAST:event_jPanelRelatCombMouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        evt.getClass();

        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        evt.getLocationOnScreen();
        //setColor(jPanel2);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        evt.getLocationOnScreen();
        //resetColor(jPanel2);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanelRelatVendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatVendMouseClicked
        // TODO add your handling code here:
        evt.getClass();
        Connection con = Conexao.getConnection();

            String src = "finalVendas.jasper";

            JasperPrint jasperPrint = null;
            try {

                
                jasperPrint = JasperFillManager.fillReport(src, null, con);
            } catch (JRException ex) {
                System.out.println("Error: " + ex);
            }

            JasperViewer view = new JasperViewer(jasperPrint, false);
            view.setVisible(true);

       
       
    }//GEN-LAST:event_jPanelRelatVendMouseClicked

    private void jPanelRelatVendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatVendMouseEntered
        // TODO add your handling code here:
        evt.getLocationOnScreen();
        setColor(jPanelRelatVend);
    }//GEN-LAST:event_jPanelRelatVendMouseEntered

    private void jPanelRelatVendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatVendMouseExited
        // TODO add your handling code here:
        evt.getLocationOnScreen();
        resetColor(jPanelRelatVend);
    }//GEN-LAST:event_jPanelRelatVendMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        evt.getClass();
    }//GEN-LAST:event_jLabel1MouseClicked

      public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(239, 24, 14));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(232,81,74));
 }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRelatorioF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRelatorioF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRelatorioF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRelatorioF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRelatorioF().setVisible(true);
            }
        });
    }

    
}
